version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    versioning-strategy: "increase-if-necessary"
    labels:
      - "maintenance"
      - "dependencies"
    groups:
      doc-deps:
        patterns:
        - "*sphinx*"
        - "toml"
      src-deps:
        patterns:
        - "ansys-grantami-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
    groups:
       actions:
          patterns:
            - "*"
